# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  # pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b53208ba-37f0-45d6-acdb-4e6a6236107a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FD5E-7468";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/c" = {
    device = "/dev/disk/by-partuuid/575a639e-5cbb-4b13-8731-d6f64911d3a2";
    fsType = "ntfs3";
    options = ["nosuid" "nodev" "uid=1000" "gid=100" "iocharset=utf8" "uhelper=udisks2"];
  };

  fileSystems."/mnt/m" = {
    device = "/dev/disk/by-partuuid/af5c36a0-2efa-4003-89f0-12a42fa484fc";
    fsType = "ntfs3";
    options = ["nosuid" "nodev" "uid=1000" "gid=100" "iocharset=utf8" "uhelper=udisks2"];
  };

  fileSystems."/mnt/n" = {
    device = "/dev/disk/by-partuuid/034a8284-8025-4afd-94d8-647ee30e1b54";
    fsType = "ntfs3";
    options = ["nosuid" "nodev" "uid=1000" "gid=100" "iocharset=utf8" "uhelper=udisks2"];
  };

  fileSystems."/mnt/o" = {
    device = "/dev/disk/by-partuuid/0ff501b0-7da3-407b-b0f8-570821d5a6a8";
    fsType = "ntfs3";
    options = ["nosuid" "nodev" "uid=1000" "gid=100" "iocharset=utf8" "uhelper=udisks2"];
  };

  fileSystems."/mnt/p" = {
    device = "/dev/disk/by-partuuid/5632fa0b-6268-4308-953c-8cd4eb3a4f20";
    fsType = "ntfs3";
    options = ["nosuid" "nodev" "uid=1000" "gid=100" "iocharset=utf8" "uhelper=udisks2"];
  };

  fileSystems."/mnt/q" = {
    device = "/dev/disk/by-uuid/cc4b40dd-6534-4056-babc-afacf96710f5";
    fsType = "ext4";
    options = ["nosuid" "nodev" "errors=remount-ro" "uhelper=udisks2"];
  };

  fileSystems."/mnt/r" = {
    device = "/dev/disk/by-partuuid/00016c1d-a940-4b26-c00b-da013ad80200";
    fsType = "ext4";
    options = ["nosuid" "nodev" "errors=remount-ro" "uhelper=udisks2"];
  };

  fileSystems."/mnt/u" = {
    device = "/dev/disk/by-uuid/03539db8-08d2-425e-98e6-435d5657f2e0";
    fsType = "ext4";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
